force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>This is used to track important alerts created by users for a given record.</description>
    <label>Alert</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alert__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A detailed description of the Alert.</description>
    <inlineHelpText>Give the details about the Alert.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Holds the sfdc record id of the Parent object. This is used as a fake way to setup a polymorphic lookup.</description>
    <externalId>true</externalId>
    <label>Parent</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Pinned__c.field-meta.xml
<CustomField>
    <fullName>Pinned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to pin alerts to the top of the alerts list.</description>
    <inlineHelpText>Pin this item to the top of the Alerts list.</inlineHelpText>
    <label>Pinned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/sObjectType__c.field-meta.xml
<CustomField>
    <fullName>sObjectType__c</fullName>
    <description>This mimics the standard sObjectType field lookup functionality. This is also set as an External Id so that it can be indexed.  Yay</description>
    <externalId>true</externalId>
    <label>sObjectType</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Rank the priority of the alert from low to high.</description>
    <inlineHelpText>Rank the priority of the Alert from low to high.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/classes/AlertsController.cls
public with sharing class AlertsController {
@AuraEnabled
    public static List<Alert__c> getAlerts(String sObjectType, String parentId) {
        return [SELECT Id,LastModifiedDate, Name,Type__c,Pinned__c,Description__c 
        FROM Alert__c where sObjectType__c = :sObjectType and Parent__c = :parentId 
        ORDER BY Pinned__c desc, lastmodifieddate DESC ];
    }

@AuraEnabled
    public static String toggleAlertPin(Alert__c alert){
        String status;
        if(alert == null) throw new AuraHandledException('No Alert found.');

        alert.Pinned__c = !alert.Pinned__c;
        try {
            update alert;
            status  = 'SUCCESS';
        } catch(Exception e) {
            throw new AuraHandledException('Oops! Couldn\'t update the Alert. Please try again.');
        }
        return status;
    }
}