force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>This is used to track important alerts created by users for a given record.</description>
    <label>Alert</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alert__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A detailed description of the Alert.</description>
    <inlineHelpText>Give the details about the Alert.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <description>Holds the sfdc record id of the Parent object. This is used as a fake way to setup a polymorphic lookup.</description>
    <externalId>true</externalId>
    <label>Parent</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Pinned__c.field-meta.xml
<CustomField>
    <fullName>Pinned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to pin alerts to the top of the alerts list.</description>
    <inlineHelpText>Pin this item to the top of the Alerts list.</inlineHelpText>
    <label>Pinned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/sObjectType__c.field-meta.xml
<CustomField>
    <fullName>sObjectType__c</fullName>
    <description>This mimics the standard sObjectType field lookup functionality. This is also set as an External Id so that it can be indexed.  Yay</description>
    <externalId>true</externalId>
    <label>sObjectType</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Rank the priority of the alert from low to high.</description>
    <inlineHelpText>Rank the priority of the Alert from low to high.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/classes/AlertsController_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class AlertsController_Test {

    @TestSetup
    static void makeData(){
        Account acct = new Account(name='Bob\'s Burgers');
        insert acct;

        List<Alert__c> alerts = new List<Alert__c>();
        Integer amountOfRecordsToCreate = 4;

        List<String> prioritiesPicklistValues = new List<String>{'High', 'Medium','Low'};
        for(Integer i = 0; i<amountOfRecordsToCreate; i++) {
            Alert__c alert = new Alert__c();
            alert.name='Blimey doubloon brig hogshead lookout';
            alert.Description__c='Coxswain overhaul hogshead ballast draught splice the main brace sutler lad. Nelsons folly hearties splice the main brace fire in the hole coffer jury mast Barbary Coast swab. Provost Nelsons folly topsail walk the plank pirate carouser gibbet Yellow Jack.';
            alert.Pinned__c=false;
            alert.Parent__c=acct.Id;
            alert.sObjectType__c='Account';
            alert.Type__c = prioritiesPicklistValues.get(Integer.valueOf(Math.floor(Math.random() * prioritiesPicklistValues.size())));
            alerts.add(alert);
        }

        // Let's party
        insert alerts;
    }

    @isTest
    static void getAlertsTestSuccess() {
        // Setup
        List<Alert__c> alerts = new List<Alert__c>();
        String sObjectType = 'Account';
        Account parent = [SELECT Id, Name from Account limit 1];
        
        // Execute
        alerts = AlertsController.getAlerts(sObjectType,parent.Id);

        // Assert
        System.debug('Parent: ' +parent.name);
        System.debug('Alerts: ' +alerts.size());
        System.assertNotEquals(null, parent.Id);
        System.assertEquals(true, alerts.size() > 0);

        // Teardown
    }

    @isTest
    static void testToggleAlertPinWithNullAlert() {
        // Setup
        String result;

        // Execute
        try { result = AlertsController.toggleAlertPin(null); } 
        catch(AuraHandledException e) { result = e.getMessage(); }

        // Assertions
        System.assertEquals('Script-thrown exception', result);
    }

    @isTest
    static void testToggleAlertPinSuccess() {
        // Setup
        String result;
        makeData();
        Alert__c alert = [SELECT id, Pinned__c from Alert__c limit 1];

        // Execute
        try { result = AlertsController.toggleAlertPin(alert); } 
        catch(AuraHandledException e) { result = e.getMessage(); }

        // Assertions
        Alert__c updatedAlert = [SELECT id, Pinned__c from Alert__c where id =: alert.id ];
        System.assertEquals(true, updatedAlert.Pinned__c);
        System.assertEquals('SUCCESS', result);
    }
}